title: "Shock Wave Analysis"
description: "PDE model, theoretical analysis, and numerical demonstration"
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

markdown: kramdown

kramdown:
  math_engine: mathjax
  input: GFM


mathjax: true

defaults:
  - scope:
      path: ""
    values:
      layout: single

